# Permalinks
permalink:           pretty

# Setup
title:               Online Judge
tagline:             leetcode, lintcode, hackerank
# url:
paginate:            1
baseurl:             "/onlineJudge"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Del Bao
  url:               
  email:             dbao@ncsu.edu

#image
image:
  source: /images/
  output: generated
  presets:
    # Proportional preset
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    # Scaled and cropped preset
    half:
      width: 400
height: 400

# Custom vars
version:             2.0.0
github:
  repo:              

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
